### ISSUE TITLE
update your project to use newer react-script because react-dev-utils is breaking

### ISSUE THREAD

**Issue by jay51** [KBHomes3/FindFoodApp#1]
hey @KBHomes3 When i tried install the dependences for your app and run it, it was breaking wit error: 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```
for more details check this issue: https://github.com/facebook/create-react-app/issues/8490
To fix this just run `npm upgrade` or the equivalent for your preferred package manager.

**Comment by KBHomes3** [comment]
thanks Jamal! its updated
